### ISSUE TITLE
Is it possible to preserve field order?

### ISSUE THREAD

**Issue by gjost** [insightindustry/sqlathanor#68]
SQLAthanor looks like a very interesting fit for a project I'm working on, with one caveat so far: it appears that the order of fields is not preserved.  It would be very useful to be able to dump to dict or JSON with the fields in the same order as they are declared in the model class or the `class.__serialization__` list.

`AttributeConfiguration` does have a `csv_sequence` arg but `dump_to_csv` doesn't seem to respect those values.

Would adding this feature be a simple matter of adding a `sqlathanor/declarative/_OrderedDict_support.py` module, or would there be lots of pain involved?

**Comment by insightindustry** [comment]
## Ordered `dict` or JSON
As it stands right now, order is not preserved when serializing from a SQLAlchemy object to a `dict`, YAML string, or JSON string. The reason is that:
* in Python, `dict` objects do not have a concept of reliable/fixed key order (although there is the `OrderedDict` class which does)
* JSON explicitly does not have key ordering

It is theoretically possible to add in `OrderedDict` support (which would probably either include a `.to_OrderedDict()` method or change the behavior of the `.to_dict()` method - I'd need to think about the best behavior), but @gjost: I'm curious if you can explain your reasoning a little more: What's the reason / use case for seeking ordering in your `dict` (or JSON) keys?

## CSV Ordering
On the CSV front, the `.dump_to_csv()` method doesn't respect the `csv_sequence` attributes because it's designed to dump _all_ of the object's attributes to a CSV, and there may be fields that do not have a `csv_sequence` attribute because they are not included at all in the `__serialization__` list. 

However, the `.to_csv()` method should respect the `csv_sequence` attribute.

That being said, there _is_ an argument to be made for `.dump_to_csv()` to respect `csv_sequence` where it is applied, and then to serialize attributes without an explicit `csv_sequence` in alphabetical order at the end of the sequence (which is the behavior for the `.to_csv()` method). 

I'll need to give this a little thought, and I might open a new feature request issue for it.

**Comment by gjost** [comment]
We have a rather special use case, in which our data is saved out to text files in JSON format and versioned by Git.  The particular fields used by data objects are set in configurations and are not hard-coded.  We use something like an OrderedDict format when writing to preserve field order.  If we didn't and fields were in random order our Git versioning would be useless.  Field order is also important in making our displays and edit forms usable (randomly ordered form fields are a UX anti-pattern).  We also offer export and import via CSV.  Field order doesn't matter to computers here either, but the CSV documents are edited by humans and a known field order is a great help there.  We also emit data via a REST API.  Again field order technically doesn't matter but when humans are evaluating the API for inclusion in their own app it's helpful.

Maintaining field order is a great convenience to users and using a data structure that maintains it makes for simpler code (in my app anyway).  Marshmallow offers this feature by default, though it's missing some other very nice feature that SQLAthanor has.

I'm not familiar with the internals of SQLAthanor but I imagine that an option at object creation time to use an OrderedDict for internal storage might just give you all these features for free.
