### ISSUE TITLE
flask sqlathanor csv flask_upload code help

### ISSUE THREAD

**Issue by pascale64** [insightindustry/sqlathanor#81]
Hi Chris,
I hope that you are able to help me with my code, I found you through [https://stackoverflow.com/questions/56165255/how-can-i-load-a-csv-into-a-database-with-sqlalchemy](link) I want to upload and add data to my database, either csv or json, I have a flask app running on nginx, uwsgi, and mysql, I am using sqlalchemy to communicate, I have attached a file with my code, but the part that I do not understand is the "route" and how to include your code from the above link, here is my code for "";
`    routes.py

     @bp.route('/', methods=['GET', 'POST'])
     @login_required
      def upload_csv():
         if request.method == 'POST':
            csv_file = request.files['file']
            csv_file = TextIOWrapper(csv_file, encoding='utf-8')
            csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            clients = Clients(name=row[1], Add_1=rowv[3], Add_2=row[3], ille=row[5], Region=row[6]
                               CodePostale=row[7], Pays=row[8])
            db.session.add(clients)
            db.session.commit()
        return redirect(url_for('data.upload_csv'))
    return render_template('data/index.html')`

`and here is your code;

    my_record_instances = []
    with open('large-data.csv', 'r') as csv_file:
        csv_records = csv.reader(csv_file, delimiter = ',')
        for row in csv_records:
            my_instance = Asset.new_from_csv(','.join(row), 
                                         delimiter = ',')
            my_record_instances.append(my_instance)`

The first code came from github and does not work, but no errors.
Can you give me an idea on how to join the two? 
warm regards
Paul
[help.txt](https://github.com/insightindustry/sqlathanor/files/3800609/help.txt)

**Comment by insightindustry** [comment]
Hi Paul,

The issue here is that within your flask application you are not actually processing the CSV file. Looking at your source code (the `help.txt` file that you shared), your core route (the `upload_csv` function) is basically doing the following:

1. It checks if the request received is using the POST HTTP method. If not, it returns an HTML page. Otherwise it proceeds to step 2.

2. Read the CSV file from the POST request.

3. Parse the CSV file and instantiate a `Client` instance for each row in the CSV file.

4. Commit the `Client` instances you have created to your database.

This logic is correct, however the logic of SQLAthanor condenses some of your steps. Here is how I would revise your code:

```
@bp.route('/', methods=['GET', 'POST'])
@login_required
def upload_csv():
    if request.method == 'POST':
        csv_file = request.files['file']
        csv_file = TextIOWrapper(csv_file, encoding='utf-8')
        csv_records = csv.reader(csv_file, delimiter = ',')
        my_record_instances = []
        for row in csv_records:
            my_instance = Client.new_from_csv(','.join(row), delimiter = ',')
            my_record_instances.append(my_instance)
        db.session.add_all(my_record_instances)
        db.session.commit()
        return redirect(url_for('data.upload_csv'))
    return render_template('data/index.html')
